### ISSUE TITLE
Uncaught Error when starting atom-cli-diff

### ISSUE THREAD

**Issue by edwardsgs** [mafiuss/atom-cli-diff#10]
Steps to reproduce below:

1. Installed atom-cli-diff
2. Restarted Atom
2. Opened two text files
4. Selected "Packages" / "Diff" / "Diff Selected Files"
5. Error Occured

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-cli-diff](https://github.com/mafiuss/atom-cli-diff) package, v0.11.0

### Stack Trace

Uncaught Error

```
At /Users/<username>/.atom/packages/atom-cli-diff/lib/diff.coffee:32

undefined
```

### Commands

```
     -0:24.6 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-seti-ui)
     -0:00.4 diff:selected (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter",
      "compare-files",
      "sort-lines",
      "tabularize"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v0.11.0
language-salt, v0.2.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by barata0** [comment]
atom-cli-diff needs TWO files selected at the tree-view pane. Not just opening the files. In fact you don't even need to open the files. Just select two files, right click "Diff selected files"
