### ISSUE TITLE
Add better feedback when two files are identical.

### ISSUE THREAD

**Issue by Zireael07** [mafiuss/atom-cli-diff#11]
If I click two files and choose the diff option, I get a temporary file, with a string of numbers as name, but no diff ever happens.

**Comment by mafiuss** [comment]
That happens when the files are identical, will mark this as enhancement and repurpose it for implenting some kind of feedback when files are identical.

**Comment by Zireael07** [comment]
Checked again, they are not identical and the other diff package diffs them just fine.
This is on Atom 1.0.2 and cli-diff 1.1.0.
