### ISSUE TITLE
Diff selected files returns an empty file

### ISSUE THREAD

**Issue by marcos-mestre** [mafiuss/atom-cli-diff#3]
When trying to do a diff between two selected files, the Atom returns an empty file. In the log console it returns:

`there was an error Error: Command failed: diff: $/home/marcos/Documents/QA-Testing/Scripts/Merchants_Red/ap_invisible.sql: No such file or directory`

`diff: $/home/marcos/Documents/QA-Testing/Scripts/Merchants_Red/ap_on_challenge_accept.sql: No such file or directory`

`diff-view.coffee:31`

[Atom version 0.106.0-781a51a](https://launchpad.net/~webupd8team/+archive/atom)
Atom Cli Diff version 0.6.4
SO Ubuntu 14.04.
Thank you

**Comment by carlopellegriniarchijcom** [comment]
It's the shellescape function used in the dependency
